_异常处理是 Java 中唯一官方的错误报告机制，并且通过编译器强制执行。_

1. Java标准异常：

    Throwable 这个Java类被用来表示任何可以作为异常抛出的类。Throwable 对象可以分为两种类型(Error 用来表示编译时和系统错误，除特殊情况
    外，一般不需要你关心；Exception 是可以被抛出的基本类型，在Java类库、用户方法以及运行时故障中都可能抛出Exception异常)。
    
2. 特例：RuntimeException

    RuntimeException 代表的是编程错误：
    
        (1).无法预料的错误。比如从你控制范围之外传递进来的 null 引用。
        (2).作为程序员，应该在代码中进行检查的错误。（比如对于 ArrayIndexOutOfBoundsException，就得注意一下数组的大小了。）在一个地方发生
        的异常，常常会在另一个地方导致错误。
        
3. finally用来做什么？

    因为无论try ... catch 是否捕获异常，finally中的内容都将被执行，finally非常重要，他能保证无论 try块里发生了什么，内存总是能得到释放，
    但是Java有垃圾回收机制，所以内存释放不需要我们关心。那么Java在什么时候使用 finally 呢？
    当要把除内存之外的资源恢复到他们的初始状态时，就用到finally语句。这种需要清理的资源包括：已经打开的文件或网络连接，在屏幕上画的图形，
    甚至可以是外部世界的某个开关。如下：
    
```java
// exceptions/Switch.java
public class Switch {
    private boolean state = false;
    public boolean read() { return state; }
    public void on() {
        state = true;
        System.out.println(this);
    }
    public void off() {
        state = false;
        System.out.println(this);
    }
    @Override
    public String toString() {
        return state ? "on" : "off";
    }
}
// exceptions/OnOffException1.java
public class OnOffException1 extends Exception {}
// exceptions/OnOffException2.java
public class OnOffException2 extends Exception {}
// exceptions/OnOffSwitch.java
// Why use finally?
public class OnOffSwitch {
    private static Switch sw = new Switch();
    public static void f()
            throws OnOffException1, OnOffException2 {}
    public static void main(String[] args) {
        try {
            sw.on();
            // Code that can throw exceptions...
            f();
            sw.off();
        } catch(OnOffException1 e) {
            System.out.println("OnOffException1");
            sw.off();
        } catch(OnOffException2 e) {
            System.out.println("OnOffException2");
            sw.off();
        }
    }
}
/**
on
off
*/
```

4. 在return 中使用 finally

    因为finally 永远会执行，所以可以从一个方法内的多个点返回，仍能保证重要的清理工作会执行：
    
```java

// exceptions/MultipleReturns.java
public class MultipleReturns {
    public static void f(int i) {
        System.out.println(
                "Initialization that requires cleanup");
        try {
            System.out.println("Point 1");
            if(i == 1) return;
            System.out.println("Point 2");
            if(i == 2) return;
            System.out.println("Point 3");
            if(i == 3) return;
            System.out.println("End");
            return;
        } finally {
            System.out.println("Performing cleanup");
        }
    }
    public static void main(String[] args) {
        for(int i = 1; i <= 4; i++)
            f(i);
    }
}
/**
Initialization that requires cleanup
Point 1
Performing cleanup
Initialization that requires cleanup
Point 1
Point 2
Performing cleanup
Initialization that requires cleanup
Point 1
Point 2
Point 3
Performing cleanup
Initialization that requires cleanup
Point 1
Point 2
Point 3
End
Performing cleanup
*/
```

从输出可以看出，从任何位置返回无关紧要，finally子句永远会执行。

5. Try-With-Resources 用法

```java
// exceptions/MessyExceptions.java
import java.io.*;
public class MessyExceptions {
    public static void main(String[] args) {
        InputStream in = null;
        try {
            in = new FileInputStream(
                    new File("MessyExceptions.java"));
            int contents = in.read();
            // Process contents
        } catch(IOException e) {
            // Handle the error
        } finally {
            if(in != null) {
                try {
                    in.close();
                } catch(IOException e) {
                    // Handle the close() error
                }
            }
        }
    }
}
```
优化之后
```java
// exceptions/TryWithResources.java
import java.io.*;
public class TryWithResources {
    public static void main(String[] args) {
        try(
                InputStream in = new FileInputStream(
                        new File("TryWithResources.java"))
        ) {
            int contents = in.read();
            // Process contents
        } catch(IOException e) {
            // Handle the error
        }
    }
}
```
    
    